before_script:
    - export PATH=$PATH:bin/
    - export DISPLAY=:99
stages:
    - test
    - robot
unit tests:
    stage: test
    script:
        # Build
        - /usr/bin/virtualenv --python=python2.7 .
        - ./bin/pip install -r requirements.txt
        - ./bin/buildout -c develop.cfg -t 3 -v
        # Test
        - ./bin/coverage erase
        - ./bin/coverage run -p --source=src bin/test || exit 1
        - ./bin/coverage combine
        - ./bin/coverage html
        - ./bin/coverage report
robot tests:
    stage: robot
    script:
        # Build
        - /usr/bin/virtualenv --python=python2.7 .
        - ./bin/pip install -r requirements.txt
        - ./bin/buildout -c develop.cfg -t 3 -v
        # Robot
        - ./bin/test --all -t robot
